export const metadata = {
  title: 'Terms of Service - Ultimate CSS Gradient Generator',
  description: 'Terms of Service for the Ultimate CSS Gradient Generator tool',
}

export default function TermsOfService() {
  return (
    <main className="min-h-screen bg-background py-12">
      <div className="container mx-auto px-4">
        <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>
        
        <div className="prose max-w-none">
          <p className="mb-4">Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
          
          <p className="mb-4">
            Please read these Terms of Service ("Terms", "Terms of Service") carefully before using the Ultimate CSS Gradient Generator website.
          </p>
          
          <h2 className="text-xl font-semibold mt-6 mb-4">1. Agreement to Terms</h2>
          <p className="mb-4">
            By accessing or using our service, you agree to be bound by these Terms. If you disagree with any part of the terms, you may not access the service.
          </p>
          
          <h2 className="text-xl font-semibold mt-6 mb-4">2. Intellectual Property</h2>
          <p className="mb-4">
            The content generated by our tool, such as CSS gradients, is freely available for you to use in both personal and commercial projects without attribution.
          </p>
          <p className="mb-4">
            However, the Ultimate CSS Gradient Generator website itself, including its design, code, and features, is our intellectual property. You may not duplicate, copy, or reuse any portion of the HTML, CSS, JavaScript, or visual design elements without express written permission from us.
          </p>
          
          <h2 className="text-xl font-semibold mt-6 mb-4">3. User-Generated Content</h2>
          <p className="mb-4">
            When you create and save gradients using our tool:
          </p>
          <ul className="list-disc pl-6 mb-4">
            <li>You retain all rights to the gradients you create</li>
            <li>You grant us a non-exclusive license to store and display your creations if you choose to share them</li>
            <li>You are responsible for ensuring your creations do not violate any laws or third-party rights</li>
          </ul>
          
          <h2 className="text-xl font-semibold mt-6 mb-4">4. Prohibited Uses</h2>
          <p className="mb-4">You agree not to use the service:</p>
          <ul className="list-disc pl-6 mb-4">
            <li>In any way that violates any applicable law or regulation</li>
            <li>To engage in any automated use of the system, including scraping or harvesting</li>
            <li>To attempt to impair the website's functionality or performance</li>
            <li>To upload malware or otherwise attack the service</li>
          </ul>
          
          <h2 className="text-xl font-semibold mt-6 mb-4">5. Limitation of Liability</h2>
          <p className="mb-4">
            To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from:
          </p>
          <ul className="list-disc pl-6 mb-4">
            <li>Your use or inability to use the service</li>
            <li>Any unauthorized access to or use of our servers or personal information</li>
            <li>Any interruption or cessation of transmission to or from the service</li>
          </ul>
          
          <h2 className="text-xl font-semibold mt-6 mb-4">6. Changes to Terms</h2>
          <p className="mb-4">
            We reserve the right to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms on this page and updating the "last updated" date.
          </p>
          <p className="mb-4">
            Your continued use of the service after any such changes constitutes your acceptance of the new Terms.
          </p>
          
          <h2 className="text-xl font-semibold mt-6 mb-4">7. Termination</h2>
          <p className="mb-4">
            We may terminate or suspend your access to our service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
          </p>
          
          <h2 className="text-xl font-semibold mt-6 mb-4">8. Governing Law</h2>
          <p className="mb-4">
            These Terms shall be governed and construed in accordance with the laws of [Your Country], without regard to its conflict of law provisions.
          </p>
          
          <h2 className="text-xl font-semibold mt-6 mb-4">9. Contact Us</h2>
          <p className="mb-4">
            If you have any questions about these Terms, please contact us at:<br />
            <a href="mailto:chordragon@duck.com" className="text-primary hover:underline">chordragon@duck.com</a>
          </p>
        </div>
      </div>
    </main>
  )
} 